Randomly assign peer reviews#3377
WikiEducationFoundation/WikiEduDashboard pull request #4160
Opened 2020-08-13 16:11 UTC by shashwatkathuria

## What this PR does
Fixes #3377 

## Screenshots
![Peek 2020-08-13 21-39](https://user-images.githubusercontent.com/37243661/90159189-a70dc680-ddad-11ea-9aaf-fa1b98865435.gif)
![Uploading Peek 2020-08-13 21-38.gif…]()

2020-08-13 16:16 UTC, shashwatkathuria commented
@ragesoss I have the following questions:
- What to do if the number of articles user has already been reviewing, is greater than `course.peer_review_count`?
- I told you earlier that I would be using `random=true` (or false) but what I did here was made the same distinction on the basis of whether `title` is provided in the query parameters or not....Is that fine?

2020-08-13 17:26 UTC, ragesoss commented
Peer review count is selected via the assignment wizard (and saved when the user submits their wizard selections, in `WizardTimelineManager`).

I think if it's nil, assigning one reviewer is probably the best option for now. Maybe later, we could add the option to set or modify the number at the time you assign them.

If a user is already reviewing the right number of articles (or more) then they should not be assigned additional ones. And if a user, for example, has 1 assigned already but the target is 3, then they should just be assigned 2 more.

The main purpose of this is to make it very easy for an instructor to randomly assign peer reviews for the entire class, so this feature should work for the entire set of students at once (and not one student at a time).

I think the shortcut of switching behavior based on whether the `title` param is provided is not as easy to understand as having an explicit `random` param (which could be omitted except when it's needed).

2020-08-14 20:00 UTC, shashwatkathuria commented
Yep, done!

2020-09-06 18:17 UTC, shashwatkathuria commented on app/controllers/assignments_controller.rb
> +    if assignment_params[:random].present?
Okay, done!

2020-09-06 18:18 UTC, shashwatkathuria commented on app/controllers/assignments_controller.rb
> +    AssignmentManager.new(user_id: nil, course: @course, wiki: @wiki,
Done!

2020-09-06 19:03 UTC, shashwatkathuria commented on config/locales/en.yml
> +      confirm_addition: Are you sure you want to assign article(s) randomly to each student?
Done!

2020-09-08 19:00 UTC, ragesoss requested changes
I tested it out, and I think it's working very smoothly! Just a few more minor suggestions from code review.

Are you still working on a feature spec?

2020-09-08 22:29 UTC, shashwatkathuria commented on lib/assignment_manager.rb
> +    @course.peer_review_count = 1
Done!

2020-09-08 22:29 UTC, shashwatkathuria commented on app/controllers/assignments_controller.rb
> +    params.permit(:id, :user_id, :course_id, :title, :random, :role, :language, :project, :status)
Nope, forgot to remove...removed it

2020-09-08 22:29 UTC, shashwatkathuria commented on app/controllers/assignments_controller.rb
> +  def create_random_peer
Done!

2020-09-08 22:29 UTC, shashwatkathuria commented on app/controllers/assignments_controller.rb
> +    raise NotPermittedError unless current_user.instructor?(@course)
Done!

2020-09-08 22:30 UTC, shashwatkathuria commented on lib/assignment_manager.rb
> +    set_peer_review_count if @course.peer_review_count.nil?
Done!

2020-09-08 22:30 UTC, shashwatkathuria commented
@ragesoss I have completed the feature spec

2020-09-10 16:08 UTC, ragesoss commented on spec/features/random_peer_review_spec.rb
> +           role: Assignment::Roles::ASSIGNED_ROLE, wiki: course.home_wiki, article: Article.first)
Using `Article.first` and the like isn't the best way to do this in a spec. It's essentially a magic number that relies implicitly on the order of creation, so it's hard-coding an invisible bit of coupling.

One better option would be to use `let` to create the articles with specific names.

2020-09-10 16:09 UTC, ragesoss commented on spec/features/random_peer_review_spec.rb
> +    create(:campaigns_course, campaign_id: campaign.id, course_id: course.id)
It's slightly more concise to do `campaign: campaign, course: course` instead of explicitly using the IDs.

2020-09-10 16:26 UTC, merged

2020-09-10 18:33 UTC, shashwatkathuria commented
For reference, further changes related to this PR: https://github.com/WikiEducationFoundation/WikiEduDashboard/commit/5606697b9df001228ea1ce85866341e6351a4a10#diff-201936fa34be34f3601f6383169ec970R12